package tesoreria.compras.ordencompra.infrastructure.persistence.adapter;
import lombok.RequiredArgsConstructor; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Component; import org.springframework.transaction.annotation.Transactional; import org.springframework.data.jpa.domain.Specification; import tesoreria.compras.ordencompra.domain.model.*; import tesoreria.compras.ordencompra.domain.ports.out.OrdenCompraRepository; import tesoreria.compras.ordencompra.infrastructure.persistence.mapper.OrdenCompraPersistenceMapper; import tesoreria.compras.ordencompra.infrastructure.persistence.repository.JpaOrdenCompraRepository; import java.util.*;
@Component @RequiredArgsConstructor public class JpaOrdenCompraRepositoryAdapter implements OrdenCompraRepository {
 private final JpaOrdenCompraRepository repository; private final OrdenCompraPersistenceMapper mapper; private final JdbcTemplate jdbc;
 @Transactional public long reservarSiguienteNumero(int anio){jdbc.update("INSERT INTO compra_orden_secuencia (anio, ultimo_numero) VALUES (?, LAST_INSERT_ID(1)) ON DUPLICATE KEY UPDATE ultimo_numero = LAST_INSERT_ID(ultimo_numero + 1)",anio);return Objects.requireNonNull(jdbc.queryForObject("SELECT LAST_INSERT_ID()",Long.class));}
 @Transactional public OrdenCompra save(OrdenCompra o){return mapper.toDomain(repository.save(mapper.toEntity(o)));}
 @Transactional(readOnly=true) public Optional<OrdenCompra> findById(Long id){return repository.findById(id).map(mapper::toDomain);} @Transactional public Optional<OrdenCompra> findByIdForUpdate(Long id){return repository.findByIdForUpdate(id).map(mapper::toDomain);} @Transactional(readOnly=true) public Optional<OrdenCompra> findByNumero(String n){return repository.findByNumero(n).map(mapper::toDomain);}
 @Transactional(readOnly=true) public List<OrdenCompra> findByCriteria(OrdenCompraCriteria c){Specification<tesoreria.compras.ordencompra.infrastructure.persistence.entity.OrdenCompraEntity> s=(r,q,b)->{var p=new ArrayList<jakarta.persistence.criteria.Predicate>();if(c.estado()!=null)p.add(b.equal(r.get("estado"),c.estado().name()));if(c.proveedorId()!=null)p.add(b.equal(r.get("proveedorId"),c.proveedorId()));if(c.sedeId()!=null)p.add(b.equal(r.get("sedeId"),c.sedeId()));if(c.fechaDesde()!=null)p.add(b.greaterThanOrEqualTo(r.get("fechaEmision"),c.fechaDesde()));if(c.fechaHasta()!=null)p.add(b.lessThanOrEqualTo(r.get("fechaEmision"),c.fechaHasta()));return b.and(p.toArray(jakarta.persistence.criteria.Predicate[]::new));};return repository.findAll(s).stream().map(mapper::toDomain).toList();}
}
