package tesoreria.compras.ordencompra.infrastructure.web.controller;
import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import tesoreria.compras.ordencompra.application.service.OrdenCompraService; import tesoreria.compras.ordencompra.domain.model.*; import tesoreria.compras.ordencompra.infrastructure.web.dto.*; import tesoreria.compras.ordencompra.infrastructure.web.mapper.OrdenCompraDtoMapper; import java.net.URI; import java.time.LocalDate; import java.util.List;
@RestController @RequestMapping("/api/tesoreria/compras/ordenCompra") @RequiredArgsConstructor public class OrdenCompraController {
 private final OrdenCompraService service; private final OrdenCompraDtoMapper mapper;
 @PostMapping public ResponseEntity<OrdenCompraResponse> create(@Valid @RequestBody OrdenCompraRequest r){var o=service.create(r.fechaEmision(),r.proveedorId(),r.sedeId(),r.observaciones(),mapper.toItems(r.items()));return ResponseEntity.created(URI.create("/api/tesoreria/compras/ordenCompra/"+o.id())).body(mapper.toResponse(o));}
 @GetMapping("/{id}") public OrdenCompraResponse get(@PathVariable Long id){return mapper.toResponse(service.get(id));} @GetMapping("/numero/{numero}") public OrdenCompraResponse getByNumero(@PathVariable String numero){return mapper.toResponse(service.getByNumero(numero));}
 @GetMapping public List<OrdenCompraResponse> list(@RequestParam(required=false) OrdenCompraEstado estado,@RequestParam(required=false) Integer proveedorId,@RequestParam(required=false) Integer sedeId,@RequestParam(required=false) LocalDate fechaDesde,@RequestParam(required=false) LocalDate fechaHasta){return service.list(new OrdenCompraCriteria(estado,proveedorId,sedeId,fechaDesde,fechaHasta)).stream().map(mapper::toResponse).toList();}
 @PutMapping("/{id}") public OrdenCompraResponse update(@PathVariable Long id,@Valid @RequestBody OrdenCompraRequest r){return mapper.toResponse(service.update(id,r.fechaEmision(),r.proveedorId(),r.sedeId(),r.observaciones(),mapper.toItems(r.items())));} @PostMapping("/{id}/{accion:aprobar|enviar|factura-parcial|cumplida-parcial|cumplida|anular}") public OrdenCompraResponse transition(@PathVariable Long id,@PathVariable String accion){return mapper.toResponse(service.transition(id,switch(accion){case "aprobar"->OrdenCompraEstado.APROBADA;case "enviar"->OrdenCompraEstado.ENVIADA;case "factura-parcial"->OrdenCompraEstado.FACTURA_PARCIAL;case "cumplida-parcial"->OrdenCompraEstado.CUMPLIDA_PARCIAL;case "cumplida"->OrdenCompraEstado.CUMPLIDA;case "anular"->OrdenCompraEstado.ANULADA;default->throw new IllegalArgumentException("Acción inválida");}));}
}
